<div>
    @include('components.landing.header')
    @include('components.landing.hero-section')
    @include('components.landing.content-section')
    @include('components.landing.works-section')
    @include('components.landing.people-section')
    @include('components.landing.blog-section')
    @include('components.landing.customer-section')
    @include('components.landing.footer')
</div>
